### PR TITLE
More benchmark experiments

### PR DESCRIPTION
**Pull request by felixbiessmann**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TammoR** [comment]
After Philipp's integration of the updated ```.complete()``` functionality, this should not be merged and thus closed, right?

**Comment by felixbiessmann** [comment]
Yes, we should close it.

Just one thing: the benchmark experiments are not merged yet, should we do
that?

Tammo Rukat <notifications@github.com> schrieb am Mo., 6. Mai 2019, 21:53:

**Comment by tdhd** [comment]
Felix, do you mean everything under `experiments/*`? What about the `benchmark_results_old.json` file?

**Comment by felixbiessmann** [comment]
Sorry I just meant the benchmarks.py and maybe the new results file

Philipp Schmidt <notifications@github.com> schrieb am Di., 7. Mai 2019,
10:01:

**Comment by TammoR** [comment]
Are we worried about the added dependency on fancyimpute?

**Comment by felixbiessmann** [comment]
re dependencies: yes, that's not ideal, especially because [I needed some bash scripting to automate installation of a sklearn version that's not pip installable yet](https://github.com/awslabs/datawig/pull/99/files#diff-dead82337eb7a4df63c6290d8f4391dd).

I just thought it'd be good to have that benchmarks code in the main repo. 

The required dependencies are in [a dedicated requirements.benchmarks.txt file](https://github.com/awslabs/datawig/pull/99/files#diff-f43cdf6bbd406be3a8eaad2cb48b6e87)

**Comment by tdhd** [comment]
Extracted benchmarks and results here https://github.com/awslabs/datawig/pull/104.

**Pull request closed without merging**
